---
- name: Traefik
  hosts: all
  tasks:

    - name: Create traefik config dir
      become: true
      file: path=/etc/traefik state=directory mode=0755

    - name: Traefik config
      become: true
      notify: restart_traefik_container
      copy:
        dest: /etc/traefik/traefik.toml
        content: |
          [entryPoints]
              [entryPoints.http]
              address = "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:80"
              [entryPoints.traefik]
              address = "{{ hostvars[inventory_hostname]['ansible_tailscale0']['ipv4']['address'] }}:8081"

          [api]
              dashboard = true
              insecure  = true

          # Enable Consul Catalog configuration backend.
          [providers.consulCatalog]
              prefix           = "traefik"
              exposedByDefault = false

              [providers.consulCatalog.endpoint]
                address = "{{ hostvars[inventory_hostname]['ansible_tailscale0']['ipv4']['address'] }}:8500"
                scheme  = "http"

    - name: Container present
      docker_container:
        name: traefik
        state: started
        image: traefik:2.7
        network_mode: host
        volumes: /etc/traefik/traefik.toml:/etc/traefik/traefik.toml

  handlers:

    - name: restart_traefik_container
      docker_container:
        name: traefik
        restart: true