---
- name: Firewall
  hosts: all
  tasks:

    - name: Install deps
      become: true
      apt:
        pkg:
        - iptables-persistent
        state: latest
        update_cache: true

    - name: Allow incoming traffic via tailscale network
      ansible.builtin.iptables:
        chain: INPUT
        in_interface: tailscale0
        jump: ACCEPT
      become: yes

    - name: Allow outgoing traffic via tailscale network
      ansible.builtin.iptables:
        chain: OUTPUT
        out_interface: tailscale0
        jump: ACCEPT
      become: yes

    - name: Allow all incoming SSH
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        jump: ACCEPT
        destination_port: 22
        ctstate: [NEW,ESTABLISHED]
        match: conntrack
      become: yes

    - name: Allow incoming HTTP / HTTPS via tcp
      ansible.builtin.iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: tcp
        destination_ports: [80,443]
        in_interface: enp1s0
        ctstate: [NEW,ESTABLISHED]
        match: conntrack
      become: yes

    - name: Allow incoming HTTP3 via udp
      ansible.builtin.iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: udp
        destination_ports: 443
        in_interface: enp1s0
        ctstate: [NEW,ESTABLISHED]
        match: conntrack
      become: yes

    - name: Allow all outgoing traffic on public ip
      ansible.builtin.iptables:
        chain: OUTPUT
        out_interface: enp1s0
        jump: ACCEPT
      become: yes

    - name: Drop all incoming traffic on public ip
      ansible.builtin.iptables:
        chain: INPUT
        in_interface: enp1s0
        jump: DROP
      become: yes

    - name: Save iptables
      become: yes
      command: netfilter-persistent save
